<a href="https://colab.research.google.com/github/Shafaq88/numpy-assignment/blob/main/numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
#task 1
marks= np.array([10, 20, 30, 40, 50])
print("\nAverage Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print(np.sum(marks))
print(marks)


Average Marks: 30.0
Highest Marks: 50
Lowest Marks: 10
150
[10 20 30 40 50]


In [7]:
#task 2
marks= np.array([45, 80, 30, 90, 55, 20])
print(marks[marks >= 50])

[80 90 55]


In [8]:
#task 3
marks = np.array([1, 2, 3, 4, 5, 6])
new_array = marks.reshape(2, 3)

print(new_array)

[[1 2 3]
 [4 5 6]]


In [9]:
#task 4
marks = np.random.randint(40, 101, 10)

print("Random Marks:", marks)
print("Average:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))

Random Marks: [ 59  44  80  59  56  73  62  70 100  45]
Average: 64.8
Highest Marks: 100
Lowest Marks: 44


In [10]:
#task 5
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])
passed = marks[marks >= 50]
failed = marks[marks < 50]

print("Passed Marks:", passed)
print("Failed Marks:", failed)

print("Number of Passed Students:", len(passed))
print("Number of Failed Students:", len(failed))

Passed Marks: [67 89 90 70 58]
Failed Marks: [35 45 22]
Number of Passed Students: 5
Number of Failed Students: 3


In [11]:
#practice
#ndim
arr = np.array([10, 20, 30, 40, 50])

print("Dimensions:", arr.ndim)

Dimensions: 1


In [12]:
#shape
marks = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Shape:", marks.shape)

Shape: (2, 3)


In [13]:
#size
marks = np.array([10, 20, 30, 40, 50])

print("Total Elements:", marks.size)

Total Elements: 5


In [14]:
#dtype
marks = np.array([10, 20, 30, 40, 50])

print("Data Type:", marks.dtype)

Data Type: int64


In [15]:
#indexing
marks = np.array([50, 60, 70, 80, 90])

print("First Mark:", marks[0])
print("Third Mark:", marks[2])
print("Last Mark:", marks[-1])

First Mark: 50
Third Mark: 70
Last Mark: 90


In [16]:
#slicing
marks = np.array([10, 20, 30, 40, 50, 60])

print("Sliced Array:", marks[1:4])

Sliced Array: [20 30 40]


In [17]:
#vectorized operation
marks = np.array([10, 20, 30, 40, 50])

print("Add 5:", marks + 5)
print("Multiply by 2:", marks * 2)
print("Subtract 5:", marks - 5)

Add 5: [15 25 35 45 55]
Multiply by 2: [ 20  40  60  80 100]
Subtract 5: [ 5 15 25 35 45]


In [18]:
#flatten
marks = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(marks)

print("Flatten Array:")
print(marks.flatten())

2D Array:
[[1 2 3]
 [4 5 6]]
Flatten Array:
[1 2 3 4 5 6]
